# Generated by Django 5.0.3 on 2024-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
        migrations.AddField(
            model_name='todolist',
            name='mail',
            field=models.IntegerField(default=1),
        ),
    ]
