# Generated by Django 5.0.3 on 2024-03-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_todolist_completed_todolist_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='tittle',
            new_name='title',
        ),
    ]
