# Generated by Django 5.0.3 on 2024-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
