# Generated by Django 5.0.3 on 2024-03-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patientrecord_delete_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
