# Generated by Django 5.0.3 on 2024-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_patientrecord_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
