# Generated by Django 5.0.3 on 2024-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_patientrecord_created_at_patientrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
