# Generated by Django 5.0.3 on 2024-03-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_patientrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100)),
                ('pred', models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3'), ('4', 'Type 4'), ('5', 'Type 5')], max_length=100)),
                ('medicine', models.CharField(choices=[('medicine1', 'Medicine 1'), ('medicine2', 'Medicine 2'), ('medicine3', 'Medicine 3'), ('medicine4', 'Medicine 4'), ('medicine5', 'Medicine 5'), ('medicine6', 'Medicine 6'), ('medicine7', 'Medicine 7'), ('medicine8', 'Medicine 8'), ('medicine9', 'Medicine 9'), ('medicine10', 'Medicine 10'), ('medicine11', 'Medicine 11'), ('medicine12', 'Medicine 12'), ('medicine13', 'Medicine 13'), ('medicine14', 'Medicine 14'), ('medicine15', 'Medicine 15'), ('medicine16', 'Medicine 16'), ('medicine17', 'Medicine 17'), ('medicine18', 'Medicine 18'), ('medicine19', 'Medicine 19'), ('medicine20', 'Medicine 20'), ('medicine21', 'Medicine 21'), ('medicine22', 'Medicine 22'), ('medicine23', 'Medicine 23'), ('medicine24', 'Medicine 24'), ('medicine25', 'Medicine 25'), ('medicine26', 'Medicine 26'), ('medicine27', 'Medicine 27'), ('medicine28', 'Medicine 28'), ('medicine29', 'Medicine 29'), ('medicine30', 'Medicine 30')], max_length=100)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(choices=[('pill', 'Pill'), ('bottle', 'Bottle')], max_length=100)),
                ('way', models.IntegerField(choices=[('1', 'Way 1'), ('2', 'Way 2'), ('3', 'Way 3'), ('4', 'Way 4')])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patientrecord')),
            ],
        ),
    ]
