# Generated by Django 5.0.3 on 2024-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_medicalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
