# Generated by Django 5.0.3 on 2024-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_medicalreport_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='medicine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='pred',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='way',
            field=models.CharField(max_length=100),
        ),
    ]
