# Generated by Django 5.0.3 on 2024-05-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_medicalexamination_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedpatientlist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='detailedpatientlist',
            name='disease_type',
        ),
        migrations.RemoveField(
            model_name='detailedpatientlist',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='detailedpatientlist',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='medicalexamination',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalexamination',
            name='patient',
        ),
        migrations.AddField(
            model_name='detailedpatientlist',
            name='patientlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patientlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='num_med',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='patientlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patientlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='way',
            field=models.CharField(choices=[('cach_1', 'Cách 1'), ('cach_2', 'Cách 2'), ('cach_3', 'Cách 3'), ('cach_4', 'Cách 4')], default='cach_1', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='disease_prediction',
            field=models.CharField(choices=[('benh_1', 'Bệnh 1'), ('benh_2', 'Bệnh 2'), ('benh_3', 'Bệnh 3'), ('benh_4', 'Bệnh 4'), ('benh_5', 'Bệnh 5')], default='benh_1', max_length=255),
        ),
    ]
