# Generated by Django 5.0.3 on 2024-05-14 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_detailedpatientlist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
