# Generated by Django 5.0.3 on 2024-05-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_patientlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='patientlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patientlist'),
        ),
    ]
