# Generated by Django 5.0.3 on 2024-05-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_medicalexamination_patientlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationstocklist',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='medicationusagereport',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='newmedication',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='newmedication',
            name='unit',
        ),
    ]
