# Generated by Django 5.0.3 on 2024-05-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_medicationstocklist_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexamination',
            name='med',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.medicationstocklist'),
            preserve_default=False,
        ),
    ]
