# Generated by Django 5.0.3 on 2024-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_medicalexamination_patientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationusagereport',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
